name: Deploy Todoist Email Reminder to AWS

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.LAMBDA_ROLE_ARN }}
          aws-region: us-west-2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Zip deployment package
        run: zip -r function.zip .

      - name: Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: "TodoistEmailReminderFunction"
          zip-file: "function.zip"
          runtime: "nodejs16.x"
          handler: "index.handler"

      - name: Cleanup
        run: rm function.zip
