# .github/workflows/deploy.yml
name: Deploy Todoist Reminder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Deploy
        working-directory: aws
        run: |
          sam build
          sam deploy \
            --stack-name todoist-reminder \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              "TodoistApiKey=${{ secrets.TODOIST_API_KEY }} SenderEmail=${{ secrets.SENDER_EMAIL }} RecipientEmail=${{ secrets.RECIPIENT_EMAIL }}"